name: 'FeedsFetcher'
description: 'Fetch websites feed and build static feeds aggregator'
branding:
  icon: archive
  color: yellow
inputs:
  opmlFile:
    description: >
      OPML file with list of feeds and category
    default: 'feeds.opml'
  outputDirectory:
    description: >
      Static feeds output directory
    default: 'contents'
  branch:
    description: >
      Output branch
    default: 'contents'
  token:
    description: >
      Github token for pulling repository information
    default: ${{ github.token }}
  customDomain:
    description: >
      Enable custom domain name for the site generator
    default: ''
runs:
  using: 'node14'
  main: 'index.js'
