name: Feeds fetcher

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  playground:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Run Action
        uses: llun/test-action@main
        with:
          customDomain: feeds.llun.dev
